spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_userActivity_db_v1
      database: fitness_userActivity_db_v1

server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

