spring:
  application:
  name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db_v1
    username: fitness_user
    password: fitness_user_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fitness_user_schema

